#!/usr/bin/env node

const childProcess = require("child_process");
const fs = require("fs");
const path = require("path");

const SCRIPT_DIR = __dirname;
const PROJECT_DIR = path.resolve(SCRIPT_DIR, "..");
const VALID_LENGTHS = new Set([128, 256, 512, 1024, 2048, 4096]);

function usage() {
  console.error(`Usage: node ${path.basename(process.argv[1])} <file.wav> <128|256|512|1024|2048|4096>`);
}

function fail(message) {
  console.error(`Error: ${message}`);
  usage();
  process.exit(1);
}

function run(command, args, options = {}) {
  const result = childProcess.spawnSync(command, args, {
    cwd: options.cwd ?? SCRIPT_DIR,
    encoding: "utf8",
    stdio: options.capture ? ["ignore", "pipe", "pipe"] : "inherit",
  });

  if (result.error) {
    fail(`${command} failed: ${result.error.message}`);
  }

  if (result.status !== 0) {
    if (options.capture && result.stderr) {
      process.stderr.write(result.stderr);
    }
    process.exit(result.status ?? 1);
  }

  return result.stdout ?? "";
}

const [, , wavPath, lengthArg, ...flags] = process.argv;

if (!wavPath || !lengthArg) {
  fail("missing arguments");
}

const irLength = Number(lengthArg);
if (!VALID_LENGTHS.has(irLength)) {
  fail("IR length must be one of: 128, 256, 512, 1024, 2048, 4096");
}

if (flags.length > 0) {
  fail(`unknown option: ${flags[0]}`);
}

const wav2irOutput = run(process.execPath, [path.join(SCRIPT_DIR, "wav2ir.js"), wavPath, String(irLength)], {
  capture: true,
  cwd: PROJECT_DIR,
});

const header = [
  "// Generated by build_ir.js. Do not edit by hand unless you know this file will not be regenerated.",
  `// Source WAV: ${wavPath}`,
  "#pragma once",
  "#include <cstddef>",
  `static constexpr size_t kIrSize = ${irLength};`,
  "",
  wav2irOutput.replace(`static const float ir[${irLength}]`, "static const float ir[kIrSize]").trim(),
  "",
].join("\n");

fs.writeFileSync(path.join(PROJECT_DIR, "generated_ir.h"), header);
