#!/usr/bin/env node

const childProcess = require("child_process");
const fs = require("fs");
const path = require("path");

const SCRIPT_DIR = __dirname;
const PROJECT_DIR = path.resolve(SCRIPT_DIR, "..");
const VALID_LENGTHS = new Set([128, 256, 512, 1024, 2048, 4096]);

function usage() {
  console.error(
    `Usage: node ${path.basename(process.argv[1])} <file.wav> <128|256|512|1024|2048|4096> [--source <file.cpp>] [--flash]`,
  );
}

function fail(message) {
  console.error(`Error: ${message}`);
  usage();
  process.exit(1);
}

function run(command, args, options = {}) {
  const result = childProcess.spawnSync(command, args, {
    cwd: options.cwd ?? SCRIPT_DIR,
    encoding: "utf8",
    stdio: options.capture ? ["ignore", "pipe", "pipe"] : "inherit",
  });

  if (result.error) {
    fail(`${command} failed: ${result.error.message}`);
  }

  if (result.status !== 0) {
    if (options.capture && result.stderr) {
      process.stderr.write(result.stderr);
    }
    process.exit(result.status ?? 1);
  }

  return result.stdout ?? "";
}

function configForLength(length) {
  if (length === 128 || length === 256) {
    return "ir_conv.cpp";
  }

  if (length === 512 || length === 1024) {
    return "ir_conv_fft.cpp";
  }

  return "ir_conv_fft_partitioned.cpp";
}

const [, , wavPath, lengthArg, ...flags] = process.argv;

if (!wavPath || !lengthArg) {
  fail("missing arguments");
}

const irLength = Number(lengthArg);
if (!VALID_LENGTHS.has(irLength)) {
  fail("IR length must be one of: 128, 256, 512, 1024, 2048, 4096");
}

let shouldFlash = false;
let sourceOverride = null;

for (let i = 0; i < flags.length; i++) {
  const flag = flags[i];

  if (flag === "--flash") {
    shouldFlash = true;
  } else if (flag === "--source") {
    sourceOverride = flags[++i];
    if (!sourceOverride) {
      fail("--source requires a file name");
    }
  } else if (flag.startsWith("--source=")) {
    sourceOverride = flag.slice("--source=".length);
    if (!sourceOverride) {
      fail("--source requires a file name");
    }
  } else {
    fail(`unknown option: ${flag}`);
  }
}

const source = sourceOverride ?? configForLength(irLength);
if (source.includes("/") || source.includes("\\") || path.extname(source) !== ".cpp") {
  fail("--source must be a .cpp file in the ir_conv directory");
}
if (!fs.existsSync(path.join(PROJECT_DIR, source))) {
  fail(`source file does not exist: ${source}`);
}

const wav2irOutput = run(process.execPath, [path.join(SCRIPT_DIR, "wav2ir.js"), wavPath, String(irLength)], {
  capture: true,
  cwd: PROJECT_DIR,
});

const header = [
  "// Generated by build_ir.js. Do not edit by hand unless you know this file will not be regenerated.",
  `// Source WAV: ${wavPath}`,
  "#pragma once",
  "#include <cstddef>",
  `static constexpr size_t kIrSize = ${irLength};`,
  "",
  wav2irOutput.replace(`static const float ir[${irLength}]`, "static const float ir[kIrSize]").trim(),
  "",
].join("\n");

fs.writeFileSync(path.join(PROJECT_DIR, "generated_ir.h"), header);

run("make", [`CPP_IR_CONV=${source}`], { cwd: PROJECT_DIR });

if (shouldFlash) {
  run("make", ["flash"], { cwd: PROJECT_DIR });
}
